# Generated by Django 3.2.6 on 2021-08-10 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренди',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Колір',
                'verbose_name_plural': 'Кольори',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(blank=True, null=True, upload_to='picture/%Y%M%D')),
                ('position', models.IntegerField()),
                ('metadata', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Зображення',
                'verbose_name_plural': 'Зображення',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('passenger', 'Passenger'), ('truck', 'Truck'), ('bus', 'Bus')], default='passenger', max_length=50)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.brand')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Моделі',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_type', models.CharField(default=0, max_length=25)),
                ('pollutant_type', models.CharField(blank=True, choices=[('a+', 'A+'), ('a', 'A'), ('b', 'B'), ('c', 'C'), ('e', 'E'), ('f', 'F'), ('g', 'G')], default='a+', max_length=10)),
                ('price', models.PositiveIntegerField(default=0)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('gas and petrol', 'Gas and Petrol'), ('hybrid', 'Hybrid')], default='diesel', max_length=25)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending Car Sell'), ('publish', 'Published'), ('sold', 'Sold'), ('archived', 'Archived')], default='pending', max_length=25)),
                ('doors', models.PositiveIntegerField(default=4)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=3)),
                ('gear_case', models.CharField(choices=[('manual transmission', 'Manual Transmission'), ('automatic transmission', 'Automatic Transmission'), ('automatic variator transmission', 'Automatic Variator Transmission'), ('automatic robotic transmission', 'Automatic Robotic Transmission')], default='manual transmission', max_length=255)),
                ('number', models.CharField(max_length=25)),
                ('slug', models.SlugField(max_length=100)),
                ('sitting_place', models.PositiveSmallIntegerField(default=5)),
                ('first_date_registration', models.DateTimeField(auto_now_add=True)),
                ('engine_power', models.PositiveSmallIntegerField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.color')),
                ('dealer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='dealers.dealer')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.model')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машини',
            },
        ),
    ]
