version: "3"

services:
  web:
    build: ./docker/python/Dockerfile.prod
    env_file:
      - .env
    ports:
      - 5000:5000
    volumes:
        - .:/usr/src/app

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2-amd64
    env_file:
      - elasticsearch.env
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    env_file:
      - kibana.env
    ports:
      - 5601:5601
